"""add role to usuarios

Revision ID: 4a33c0effb02
Revises: 
Create Date: 2026-06-08 09:32:44.950221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a33c0effb02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('role', sa.String(length=50), server_default='operador', nullable=False))
    # Define o usuário 'admin' como administrador automaticamente
    op.execute("UPDATE usuarios SET role = 'admin' WHERE nome = 'admin'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'role')
    # ### end Alembic commands ###
