"""add emails_autorizados

Revision ID: 99f45b3e9c92
Revises: 4a33c0effb02
Create Date: 2026-06-08 09:46:29.015534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '99f45b3e9c92'
down_revision: Union[str, None] = '4a33c0effb02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
